name: Exemple cicd
on:
    push:
        branches: [main]
jobs:
    job1:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:18
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Bandit
            run: pip install bandit  && bandit -r ./
          - name: Prepare postgres
            run: |
                docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:18 

                until pg_isready -h localhost -p 5432 -U postgres; do
                echo "Waiting for PostgreSQL..."
                sleep 1
                done
          - name: Prepare postgres
            env:
                PGPASSWORD: postgres
            run: psql -c 'CREATE DATABASE API' --dbname=postgres --host=localhost --username=postgres -w
          - name: Prepare db
            run: pip install alembic && alembic upgrade head
