name: Exemple cicd
on:
    push:
        branches: [main]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: step 1
            run: pip install bandit  && bandit -r ./
  