name: Exemple cicd
on:
    push:
        branches: [main]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: step 1
            run: pip install bandit  && bandit -r ./
          - name: step 2
            run: ls -l --color
  